waitUntil { !isNil "StartAttack"};
execVM "flare.sqf";
if (daytime < 9 || daytime > 18) then { [TRG_FLARE, "Flare_82mm_AMOS_White", -1, 2, 45, 10] spawn dzn_fnc_StartVirtualFiremission; } else { "" };
[mortar1,TGT1,"8Rnd_82mm_Mo_shells",150,8,10] spawn BIS_fnc_fireSupport;
[mortar2,TGT1,"8Rnd_82mm_Mo_shells",150,8,10] spawn BIS_fnc_fireSupport;
[mortar3,TGT1,"8Rnd_82mm_Mo_shells",150,8,10] spawn BIS_fnc_fireSupport;
uiSleep 30;
[advance1, [GetPosATL SAD1, GetPosATL SAD2], "SAD"] call dzn_fnc_dynai_moveGroups;
uiSleep 300;
_flarePos = [getPosASL TGT_FLARE2, random 100, random 100] call BIS_fnc_relPos;
_flare = createVehicle ["F_20mm_Red", _flarePos, [], 0, "NONE"];
_flare setPosATL [getPosATL _flare select 0, getPosATL _flare select 1, 150 + (random 75)];
_flare setVelocity [0,0,-0.1];
[advance1_2, [GetPosATL SAD3, GetPosATL SAD4], "SAD"] call dzn_fnc_dynai_moveGroups;
uiSleep 300;
secondwave = true; publicVariable "secondwave";
waitUntil { !isNil "secondwave"; };
[mortar1,TGT1,"8Rnd_82mm_Mo_shells",150,8,10] spawn BIS_fnc_fireSupport;
[mortar2,TGT1,"8Rnd_82mm_Mo_shells",150,8,10] spawn BIS_fnc_fireSupport;
[mortar3,TGT1,"8Rnd_82mm_Mo_shells",150,8,10] spawn BIS_fnc_fireSupport;
[advance2, [GetPosATL SAD1, GetPosATL SAD2], "SAD"] call dzn_fnc_dynai_moveGroups;
[advance2_2, [GetPosATL SAD3, GetPosATL SAD4], "SAD"] call dzn_fnc_dynai_moveGroups;
uiSleep 300;
[assault, getPosASL TGT1, "SAD"] call dzn_fnc_dynai_moveGroups;